<a href="https://colab.research.google.com/github/zhongwenGit/test-pytorch/blob/main/autograd_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x = torch.randn(2, 2, requires_grad=True)
print(x)

tensor([[ 1.3080, -0.1723],
        [-1.7083,  1.2584]], requires_grad=True)


In [ ]:
y = x.add(5)
print(y)

tensor([[6.3080, 4.8277],
        [3.2917, 6.2584]], grad_fn=<AddBackward0>)


In [ ]:
print(y.grad_fn)

In [ ]:
z = y * y * 3
print(z)
out = z.mean()

print(z, out)

tensor([[119.3743,  69.9189],
        [ 32.5052, 117.5018]], grad_fn=<MulBackward0>)
tensor([[119.3743,  69.9189],
        [ 32.5052, 117.5018]], grad_fn=<MulBackward0>) tensor(84.8251, grad_fn=<MeanBackward0>)


In [ ]:
a = torch.ones(2, 2)
#a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)
print(b)

False
True
tensor(4., grad_fn=<SumBackward0>)


In [ ]:
x.requires_grad_(False)

tensor([[ 1.3080, -0.1723],
        [-1.7083,  1.2584]])

In [ ]:
x.requires_grad_(True)

tensor([[ 1.3080, -0.1723],
        [-1.7083,  1.2584]], requires_grad=True)

In [ ]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

RuntimeError: ignored