<a href="https://colab.research.google.com/github/zhongwenGit/test-pytorch/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
from __future__ import print_function
import torch

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[1.9333e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 6.6032e-36]])


In [5]:
x = torch.ones(5,4,dtype=torch.float)
print (x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [6]:
x = torch.randn(3,2)
print(x)

tensor([[ 0.2100, -1.1094],
        [-0.7546, -0.4093],
        [ 1.7720, -0.4239]])


In [7]:
x=torch.tensor([[2,2,1],[1,1,2]])
print(x.shape)
print(x)

torch.Size([2, 3])
tensor([[2, 2, 1],
        [1, 1, 2]])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)
print(x.shape)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
torch.Size([5, 3])
tensor([[-0.2733, -0.2064, -0.1924],
        [ 1.9925,  0.3961, -0.8299],
        [ 0.4387,  0.3099,  1.5066],
        [-0.3429,  0.7181, -1.0234],
        [-0.8596, -1.4447,  0.2455]])


In [9]:
y = torch.rand_like(x,dtype=torch.float)
print("y shape", y.shape)
print(y)

y shape torch.Size([5, 3])
tensor([[0.8154, 0.3628, 0.5905],
        [0.0720, 0.0219, 0.5049],
        [0.1611, 0.4136, 0.5958],
        [0.8263, 0.2400, 0.6772],
        [0.3152, 0.1271, 0.7856]])


In [10]:
z = x+y
print("------x-----",x)
print("------y-----",y)
print("------Z-----",z)

------x----- tensor([[-0.2733, -0.2064, -0.1924],
        [ 1.9925,  0.3961, -0.8299],
        [ 0.4387,  0.3099,  1.5066],
        [-0.3429,  0.7181, -1.0234],
        [-0.8596, -1.4447,  0.2455]])
------y----- tensor([[0.8154, 0.3628, 0.5905],
        [0.0720, 0.0219, 0.5049],
        [0.1611, 0.4136, 0.5958],
        [0.8263, 0.2400, 0.6772],
        [0.3152, 0.1271, 0.7856]])
------Z----- tensor([[ 0.5421,  0.1564,  0.3981],
        [ 2.0645,  0.4180, -0.3250],
        [ 0.5998,  0.7234,  2.1024],
        [ 0.4833,  0.9580, -0.3462],
        [-0.5444, -1.3176,  1.0312]])


In [11]:
x.copy_(y)
print(y)
print(x.shape)
print(x)

tensor([[0.8154, 0.3628, 0.5905],
        [0.0720, 0.0219, 0.5049],
        [0.1611, 0.4136, 0.5958],
        [0.8263, 0.2400, 0.6772],
        [0.3152, 0.1271, 0.7856]])
torch.Size([5, 3])
tensor([[0.8154, 0.3628, 0.5905],
        [0.0720, 0.0219, 0.5049],
        [0.1611, 0.4136, 0.5958],
        [0.8263, 0.2400, 0.6772],
        [0.3152, 0.1271, 0.7856]])


In [12]:
x.t_()
print(x.shape)
print(x)

torch.Size([3, 5])
tensor([[0.8154, 0.0720, 0.1611, 0.8263, 0.3152],
        [0.3628, 0.0219, 0.4136, 0.2400, 0.1271],
        [0.5905, 0.5049, 0.5958, 0.6772, 0.7856]])


In [13]:
print(x[2,:])

tensor([0.5905, 0.5049, 0.5958, 0.6772, 0.7856])


In [17]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 4)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
print(x)

torch.Size([4, 4]) torch.Size([16]) torch.Size([4, 4])
tensor([[-0.2598,  1.8672, -1.4153,  1.7927],
        [-0.4008, -1.8718,  0.5752,  1.1997],
        [ 0.2193,  0.8235, -0.2668, -0.5868],
        [ 1.8673,  1.8867,  1.1624,  0.1876]])


In [18]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(x)
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[-0.2598,  1.8672, -1.4153,  1.7927],
        [-0.4008, -1.8718,  0.5752,  1.1997],
        [ 0.2193,  0.8235, -0.2668, -0.5868],
        [ 1.8673,  1.8867,  1.1624,  0.1876]], device='cuda:0')
tensor([[ 0.7402,  2.8672, -0.4153,  2.7927],
        [ 0.5992, -0.8718,  1.5752,  2.1997],
        [ 1.2193,  1.8235,  0.7332,  0.4132],
        [ 2.8673,  2.8867,  2.1624,  1.1876]], device='cuda:0')
tensor([[ 0.7402,  2.8672, -0.4153,  2.7927],
        [ 0.5992, -0.8718,  1.5752,  2.1997],
        [ 1.2193,  1.8235,  0.7332,  0.4132],
        [ 2.8673,  2.8867,  2.1624,  1.1876]], dtype=torch.float64)
